---

- include: includes/init.yml

- name: The procedures for the appropriate distribution family have been loaded.
  include: "includes/families/{{ ansible_os_family }}.yml"

- name: Install Docker.
  become: yes
  package:
    name: "{{ docker_install_package_docker_install }}"

- name: Ensure Docker is started and enabled at boot.
  become: yes
  service:
    name: "{{ docker_install_package_docker_demon }}"
    state: started
    enabled: yes

- include: includes/install_docker_compose.yml
  when: docker_install_package_docker_compose_install|bool
