---

- include: includes/init.yml

- include: includes/families/Debian.yml
  when: ansible_os_family == "Debian"

- include: includes/families/RedHat.yml
  when: ansible_os_family == "RedHat"

- name: Install Docker.
  become: yes
  package:
    name: "{{ docker_install_package_docker_install }}"

- name: Ensure Docker is started and enabled at boot.
  become: yes
  service:
    name: "{{ docker_install_package_docker_demon }}"
    state: started
    enabled: yes

- include: includes/install_docker_compose.yml
  when: docker_install_package_docker_compose_install
