---

- name: Check current docker-compose version.
  command: docker-compose --version
  register: docker_compose_current_version
  changed_when: false
  failed_when: false

- name: Delete existing docker-compose version if it's different.
  become: yes
  file:
    path: "{{ docker_install_package_docker_compose_path }}"
    state: absent
  when: >
    docker_compose_current_version.stdout is defined
    and docker_install_package_docker_compose_version not in docker_compose_current_version.stdout

- name: Install Docker Compose (if configured).
  become: yes
  get_url:
    url: "{{ docker_install_package_docker_compose_url }}"
    dest: "{{ docker_install_package_docker_compose_path }}"
    mode: 0755
